services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=pg-db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin
    volumes:
      - redis-volume:/data

volumes:
  postgres-volume:
  redis-volume:
