services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env.development
    volumes:
      - diary_app_dev_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: admin
    volumes:
      - diary_app_dev_redis:/data

volumes:
  diary_app_dev_postgres:
  diary_app_dev_redis:
